SITUATIONS = [
    {"situation": "I'm having dinner with an old friend and he suddenly asks me to borrow money. I don't want to lend him money, but I don't want to hurt his feelings. I want to get out of this situation without hurting his feelings.",
     "myObjective": "Politely decline the request while preserving the friendship"},
    {"situation": "While attending a family gathering, a relative I don't know well starts making inappropriate and offensive comments about a specific group of people.",
     "myObjective": "Diffuse the situation and steer the conversation toward a more positive topic"},
    {"situation": "A coworker constantly talks about their personal problems and makes I feel like their therapist, even though I've tried to set boundaries.",
     "myObjective": "Reinforce boundaries and encourage the coworker to seek appropriate support"},
    {"situation": "During a group project, one team member isn't contributing, and I'm unsure how to address the issue without causing conflict.",
     "myObjective": "Address the issue constructively and encourage equal participation"},
    {"situation": "At a friend's party, two guests start arguing loudly about politics, making everyone else feel uncomfortable.",
     "myObjective": "Intervene and redirect the conversation to a more neutral topic"},
    {"situation": "I receive a gift from a friend that I don't like, and I'm unsure how to express gratitude without seeming insincere.",
     "myObjective": "Thank the friend genuinely for their thoughtfulness, focusing on the gesture rather than the gift itself"},
    {"situation": "A neighbor's dog barks loudly all night, disrupting my sleep, but I don't want to damage my relationship with the neighbor.",
    "myObjective": "Politely address the issue and seek a mutually agreeable solution"},
    {"situation": "I accidentally overhear a coworker gossiping about I, and I'm unsure whether to confront them or let it go.",
    "myObjective": "Evaluate the situation and determine the best course of action to maintain a positive work environment"},
    {"situation": "A friend asks for my honest opinion on a creative project they've poured their heart into, but I don't think it's very good.",
    "myObjective": "Provide constructive feedback while being sensitive to their feelings"},
    {"situation": "I'm stuck in a long conversation with someone who has strong body odor, and I'm unsure how to politely excuse myself.",
    "myObjective": "Find a polite excuse to exit the conversation without embarrassing the person"},
    {"situation": "I discover a friend has been lying to I about something important, but confronting them might jeopardize my friendship.",
    "myObjective": "Address the issue while maintaining the friendship and building trust"},
    {"situation": "At a social event, someone I've just met starts flirting with I aggressively, and I don't know how to politely decline their advances.",
    "myObjective": "Politely and assertively communicate my disinterest while maintaining a respectful tone"},
    {"situation": "A family member consistently forgets my dietary restrictions and serves I food I can't eat, but I don't want to upset them by pointing it out.",
    "myObjective": "Gently remind them of my dietary restrictions and express appreciation for their efforts"},
    {"situation": "my boss takes credit for my work in a meeting, and I'm unsure how to address the situation without jeopardizing my job.",
    "myObjective": "Find a diplomatic way to communicate the issue and ensure proper credit is given"},
    {"situation": "A close friend starts dating someone I've had a secret crush on for a long time, and I don't know how to handle my feelings.",
    "myObjective": "Process my feelings while being supportive of my friend's happiness"},
    {"situation": "I find out that a colleague has been taking credit for my ideas in meetings with my manager.",
    "myObjective": "Address the issue professionally and ensure my contributions are recognized"},
    {"situation": "my boss assigns I a task that is beyond my skillset, but I'm afraid to ask for help or clarification.",
    "myObjective": "Seek assistance or clarification while demonstrating a willingness to learn and grow"},
    {"situation": "A coworker consistently arrives late to meetings and interrupts others, causing disruptions and delays.",
    "myObjective": "Address the behavior professionally and encourage a more respectful work environment"},
    {"situation": "I receive a promotion over a close friend at work, and I'm unsure how to maintain my friendship without creating resentment.",
    "myObjective": "Support my friend and maintain open communication to preserve the friendship"},
    {"situation": "I'm asked to give a negative performance review to a coworker who is also a personal friend.",
    "myObjective": "Provide honest, constructive feedback while maintaining the personal friendship"},
    {"situation": "A colleague frequently asks for my help with tasks, preventing I from completing my own work on time.",
    "myObjective": "Set boundaries and manage my own workload while offering appropriate support"},
    {"situation": "I'm stuck in a conversation with a coworker who complains excessively about work, making it difficult to maintain a positive attitude.",
    "myObjective": "Steer the conversation toward a more positive topic or politely excuse myself"},
    {"situation": "A team member's poor communication skills are causing confusion and delays on a project, but I'm unsure how to address the issue without causing offense.",
    "myObjective": "Encourage improved communication and offer support to enhance the team's collaboration"},
    {"situation": "I'm asked to work on a project that goes against my personal values, but I'm afraid of the consequences of refusing the assignment.",
    "myObjective": "Communicate my concerns and explore alternative assignments or solutions"},
    {"situation": "A coworker tries to engage I in office gossip, and I don't want to participate but are unsure how to politely decline.",
    "myObjective": "Politely decline involvement in the gossip and maintain a professional demeanor"}
]